### ISSUE TITLE
Add support for gt/lt/gte/lte

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/sql-concat#1]
Either `.whereGreaterThan('some_column', 10)` or `.where('some_column', '>', 10)`

Not as trivial as you'd first guess, since the idea of comparison is buried a bit deeper than it should be https://github.com/TehShrike/sql-concat/blob/3dd1aeb1c65315d3e286c03693f97bd6e0a63eec/clause-handlers.js#L72-L82

**Comment by ArtskydJ** [comment]
As far as the api goes, I would rather have `.where('some_column', '>', 10)`, and maybe this would be supported as well: `.where('some_column', 'gte', 10)`

**Comment by TehShrike** [comment]
`.where('some_column', '>', 10)` sounds good to me too.  I'll implement that when I get the chance.  If anyone beats me to it, that's fine too!

**Comment by TehShrike** [comment]
Published as 1.3.0
