### ISSUE TITLE
Change str/params to sql/values?

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/sql-concat#16]
The [`mysql`](https://github.com/mysqljs/mysql) library takes an options object with `sql` and `values` properties - maybe sql-concat should change its result/build object to use those property names so you could call `connection.query(myQuery.build())`?

**Comment by ArtskydJ** [comment]
https://github.com/TehShrike/sql-concat/blob/master/query-object.js#L59-L62
```diff
  	return {
  		params: reducedClause.params,
+ 		values: reducedClause.params,
  		str: (`${clauseQueryString} ${reducedClause.str}`).trim(),
  	}
```

Could do it without a breaking change? Maybe that's worse, though.

**Comment by daytonlowell** [comment]
I'm also willing to go the route of passing an optional options object to .build() to have it return an object that looks different. `.build({ mysql: true })` or something.
