### ISSUE TITLE
To consider: add `toString()` and handle escaping in sql-concat

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/sql-concat#17]
Right now values are not escaped by this library, it just spits out a string with question marks, and an array of parameters to be escaped.  We expect the query string and the params array to be passed to the [`mysql`](https://github.com/mysqljs/mysql/) library.

`mysql` doesn't support prepared statements yet, it's just escaping values itself.  It does provide a connection-specific escaping function, but all it does is [pass in a time zone](https://github.com/mysqljs/mysql/blob/cf5d1e396a343ffa0fba23b3791d2dd5da20f30e/lib/Connection.js#L262).

So, sql-concat could pretty easily do the escaping - it could even use [`sqlstring`](https://github.com/mysqljs/sqlstring), the same package used by `mysql` to escape values.

Upsides:
- this library wouldn't be tied to mysql
- you could use it to generate queries for other purposes

This could be done by exposing a new `toString()` method and leaving the `build()` method alone, so I don't think we would have to break backward compatibility?

**Comment by ArtskydJ** [comment]
I start to wonder if the package is trying to do too much. Is it doing one thing well? Unfortunately, splitting this into two packages would probably break backwards compat :(

Anyway... up to you. I like the idea of a query builder module not being tied to mysql.

**Comment by TehShrike** [comment]
What were you thinking the two packages would do?

I think doing the escaping here would simplify the library conceptually - right now sql-concat essentially depends on `mysql` as a peer dependency, since it relies on its specific escaping scheme.

**Comment by TehShrike** [comment]
I'm going to say this was closed by #21 – explicitly testing for compatible escaping with different database engines can be another issue if someone wants to pursue it.
